### ISSUE TITLE
I can't assign keyboard shortcuts ctrl+alt+O/P/L

### ISSUE THREAD

**Issue by Janaue** [fxsound2/fxsound-app#103]
I updated fxsound to 1.1.22.0 and I would like to keep using my usual shortcuts ctrl+alt+O/P/L, but they are inoperative.
I don't understand why because those shortcuts are not used anywhere in my other software and I don't even run other software: after a reboot with nothing launched but FxSound, I still can't get them to be activated with the red ribbon around (ribbon stays grey).
![_2024-04-01 16_12_28](https://github.com/fxsound2/fxsound-app/assets/10972636/980bb6d1-9753-4f2d-8172-6383a6bc27ed)

**Comment by doolhoofd** [comment]
Hi Janaue, 
FxSound automatically detects your existing keyboard combinations, and disables those that are already in use.
You have three options:

1. Use a different keyboard, or change your keyboard layout to a different language in your system's settings; 
2. Use different keys for those shortcuts instead of O/P/L;
3. Install an older version; you can find free downloads of all previous versions here:

https://www.videohelp.com/software/FxSound-/old-versions

I hope this was helpful. If you have any other questions, feel free to ask them.

**Comment by doolhoofd** [comment]
Come to think about it, there are probably more options than only those three. 
For example, I found this on Microsoft Support:

https://support.microsoft.com/en-us/office/customize-keyboard-shortcuts-9a92343e-a781-4d5a-92f1-0f32e3ba5b4d

And there are also programs which allow you to customize your shortcuts, a.k.a. hotkey managers.

**Comment by Janaue** [comment]
Yeah but I don't run any other programs, so how does Fxsound knows about those ctrl+alt+o/p/l ?
Is there  a software which lists all the keyboard shortcuts currently in use, and by with other software ?

I went back to 1.20.0 and here I can assign my ctrl+alt+o/p/l and when I press them, it's FxSound which responds and no other software.

**Comment by raddyst** [comment]
> Yeah but I don't run any other programs, so how does Fxsound knows about those ctrl+alt+o/p/l ?

Which is your default keyboard layout? Maybe your keyboard use vendor(non-standard) software? Which OS version do you use?

> Is there a software which lists all the keyboard shortcuts currently in use, and by which other software ?

No )

**Comment by doolhoofd** [comment]
> Is there a software which lists all the keyboard shortcuts currently in use, and by which other software ?

Did you check the above Windows settings? They should do exactly that.

https://support.microsoft.com/en-us/office/customize-keyboard-shortcuts-9a92343e-a781-4d5a-92f1-0f32e3ba5b4d

**Comment by doolhoofd** [comment]
@Janaue: Those instructions are for Microsoft Word, not Windows. I apologize. 

@raddyst: Thanks for helping out. These are good questions.

**Comment by bvijay74** [comment]
On my English keyboard, Ctrl+Alt+O and Ctrl+Alt+P results in ō and l̥ characters. A simple exercise is to try typing the keyboard combination in a text editor like notepad. If it results in any character, then that combination cannot be used in FxSound.

**Comment by Janaue** [comment]
Okay I use ''QWERTY US International''  on an ANSI QWERTY keyboard. Ctrl+Alt+O and Ctrl+Alt+P gives ó and ö in a text editor. I will try another combination.

**Comment by doolhoofd** [comment]
This seems worth adding; a helpful forum user named Hansk posted this useful information recently:

>Although this thread is somewhat cold, I do have maybe something to add.
With the current version of FS v1.1.22.0 the keyboard shortcuts seem to work.
I’m on a fully updated W11 system AND using an American International keyboard setting. No problem with that setting.
But of course there’s another issue: W11 doesn’t provide any clarity on which keyboard shortcuts are owned by which process… Not even the ‘global’ hotkeys.
I found lots of people need that clarity; how else can you know if a certain hotkey combination is already in use? Or what will you break if you ‘overrule’ an existing hotkey?
There is a tool available on the internet called Hotkey Explorer. You can download it. But please beware, DON’T use it. It will mess up your system because it will ‘push’ all the possible hotkeys and feeds it to you system. Messy, not to say the least.
I found another tool called **Hotkey Detective**. It is on GitHub, open source.
**[ [https://github.com/ITachiLab/hotkey-detective](https://github.com/ITachiLab/hotkey-detective) ]**
This really helps to find out which process owns a hotkey combination.
Though, this does not solve everything: 
A hotkey combination may be globally reserved, or by an app. The latter ones, will still be bound to that app while your using that app.
There are still 64-bit and x86 hotkey owners. So, beware to look for both options.
Some combinations don’t seem to have a global owner, but still do not work when I allocate them to FS (e.g. like Ctl Alt Q or Ctl Alt C)
Instead of Ctl Alt Q I found that Ctl Alt R does work as a globally defined hotkey in windows on my system.
Hope this helps!

Link to the forum post:

[https://forum.fxsound.com/t/issue-with-default-shortcuts/2148/11](https://forum.fxsound.com/t/issue-with-default-shortcuts/2148/11)
