### ISSUE TITLE
Clicking the X button from the alt-tab screen quits FxSound

### ISSUE THREAD

**Issue by pie-flavor** [fxsound2/fxsound-app#113]
**Describe the bug**
In the alt-tab menu, there is an X button above the window preview and it is supposed to do the same thing as clicking the X button in the application. It does not. The X button in the application minimizes it to tray and the X button in the alt-tab screen quits the application.

**To Reproduce**
1. Open FxSound from the tray menu.
1. Hold Alt+Tab.
1. While holding Alt+Tab, click the X button in the alt-tab preview.
1. Observe that the application has fully quit and the audio device has been reset.

**Expected behavior**
The application to minimize to tray, same as the X button in the application.

**Screenshots**
![image](https://github.com/fxsound2/fxsound-app/assets/17803831/308b0845-627a-43ae-9774-633a8d08784e)

**System information**
 - Windows version: 10 22H2 19045.4291
 - Audio device: Realtek drivers' virtual speakers

**Comment by doolhoofd** [comment]
Okay... I've been running Windows since childhood, and have never heard of or used this function until today.
Perhaps it follows the tray icon's own logic into the Exit option?

![Exit](https://github.com/fxsound2/fxsound-app/assets/151672060/a7bca179-7a73-4659-8713-be1c6016635f)

Hi @bvijay74;
Just curious what your opinion on this one would be?

**Comment by bvijay74** [comment]
I compared the Alt-Tab, preview window close button press behaviour in other applications. Application that minimise to the system tray are minimising and other task bar applications which don't have a system tray icon are closing. 
To make FxSound behaviour similar to other system tray applications on Windows, we have to minimise it instead of quitting the application. We can look into the code changes required for this fix.

**Comment by bvijay74** [comment]
This issue is fixed in 1.1.24.0
