### ISSUE TITLE
Inquiry about FxSound Automation Capabilities

### ISSUE THREAD

**Issue by brxndonroux** [fxsound2/fxsound-app#58]
Hello FxSound Support Team,

I hope this message finds you well. I am currently working on a script to automate certain functionalities within FxSound, and I am interested in exploring whether FxSound provides a command-line interface (CLI) or any other automation options.

The goal of the automation script is to streamline the activation process of FxSound, making it more convenient for me. If FxSound offers a CLI or any other methods for automation, I would greatly appreciate information on the available commands or interfaces.

Your guidance on this matter would be invaluable in enhancing the automation capabilities of FxSound. If there are specific resources or documentation that I should refer to, please provide the necessary details.

Thank you for your time and assistance. I look forward to hearing from you.

**Comment by raddyst** [comment]
read here - https://forum.fxsound.com/t/suggestion-control-via-command-line/2283

**Comment by brxndonroux** [comment]
Thank you!

**Comment by bvijay74** [comment]
Hi @brxndonroux 
As @raddyst has pointed out the FxSound forum discussion has the list of command line parameters that can be passed to FxSound.
Since FxSound is a free application, there is no sign-in or activation process after installation. Can you please provide more details on your requirement  - _The goal of the automation script is to streamline the activation process of FxSound_
